name: Lint

on:
  push:
    # On other branches the `pull_request` trigger will be used
    branches: [current, next]

  pull_request:
    # Only trigger on certain events (not when comments are added)
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Lint
      run: |
        python travis.py
        make html-strict
